name: magicsaves
favicon: null
layout_spectrum: 0.28129549021832645
typography_spectrum: 0.06687565939500928
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.8845644530374557
  lightness: 0.43737674597650766
  saturation: 0.17472175369039178
  rhythmicContrast: 0.6550667507108301
purpose: []
